### ISSUE TITLE
Investigate patterns and ways to implement game mechanics used in gamedev

### ISSUE THREAD

**Issue by vlad-d-markin** [vlad-d-markin/dethgame#3]
1. Game GUI
2. Inventory and pickable items
3. Damage
4. Collisions
5. Tile maps
6. Resource management (its Oxygine task I suppose, not important)
7. And anything useful

**Comment by GoAlexander** [comment]
Initial state: https://github.com/vlad-d-markin/dethgame/commit/f5ab9e1e1f5dbdc597554737530039b08cadccfa

**Comment by GoAlexander** [comment]
https://github.com/vlad-d-markin/dethgame/commit/a2ac0f449be3c378f7b85677abdf49a9b938e1e7
