### ISSUE TITLE
Fix Nathan punch animation

### ISSUE THREAD

**Issue by vlad-d-markin** [vlad-d-markin/dethgame#39]

**Comment by bhumkong** [comment]
https://github.com/vlad-d-markin/dethgame/commit/90b4678d4653dfe7c2acad3bb18e53f3f0c07cdf

**Comment by bhumkong** [comment]
https://github.com/vlad-d-markin/dethgame/commit/49eb067243abf7fb2909d99fba0db907c2a399fb
